name: Subscriptions
on:
    workflow_dispatch:

jobs:
    rss:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            include:
              - url: "https://androidweekly.net/rss.xml"
                path: "androidweekly"
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
